### PR TITLE
docs: improve getting started

### PR DESCRIPTION
**Pull request by Gorkem-Encord**
- Added references to Colab notebooks
- Updated getting started page

### CODE REVIEW

**Comment by Encord-davids** [comment]
Since PRs are squashed on merge can you please ensure the title follow our commit [convention](https://encord-active-docs.web.app/contributing/#commit-convention) 🙏

**Comment by Encord-davids** [comment]
Since @frederik-encord's [PR](https://github.com/encord-team/encord-active/pull/12) is revamping the readme, can I suggest it is merged before this one 🙏

**Comment by frederik-encord** [comment]
@Gorkem-Encord What is the state of this PR?

**Comment by Gorkem-Encord** [comment]
I need to refactor after your last changes (hello => quick start), can quickly do that after the lunch.

**Comment by Gorkem-Encord** [comment]
@frederik-encord I think it is good to go now.

**Review by frederik-encord — APPROVED** [review]

**Pull request merged**
