### PR TITLE
[FIX] replace is used instead of rename

### PR DESCRIPTION
**Pull request by feemthan**
This fix is because recent pandas update throws warnings while running the app, pandas requests replace to be used instead of rename in their documentation.

### CODE REVIEW

**Comment by Encord-davids** [comment]
> pandas requests replace to be used instead of rename in their documentation

Could you add a reference and specify the offending `pandas` version? 🙏 
So far we have successfully been using `rename` and if that is not supported anymore we would need to update all usages of it in addition to the one you are suggesting.

One caveat with `replace` is that it will also apply to substrings which might open the door for bugs 😕
E.g. we have two columns `score` and `new_score` by calling `str.column.replace("score", "old_score")` we would end up with the following columns: `["old_score", "old_score_new"]` which isn't what we want.

**Comment by feemthan** [comment]
Aah, I see the problem. The culprit is inplace = True then. This seems to work for me and will update all instances of rename.

**Comment by Encord-davids** [comment]
> Aah, I see the problem. The culprit is inplace = True then. This seems to work for me and will update all instances of rename.

I think there might be an even deeper culprit which is the fact that we create a [view instead of a copy](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy). So the warning is raised when you rename (or similar operations) in place on a view.

Since renaming isn't the only operation we do on `x_metric_df` and `y_metric_df` we will need to make a copy of them anyway ([and we do](https://github.com/encord-team/encord-active/blob/d5da934599103f32d60477ed05e17d0436012aff/src/encord_active/app/common/components/metric_summary.py#L87-L91)).

I suggest we just make a copy in the first place, which should resolve all issues. 
```python
x_metric_df = (
    metrics_data_summary.metrics[str(x_metric_name)]
    .df[[MetricWithDistanceSchema.identifier, MetricWithDistanceSchema.score]]
    .copy()
)
```

**Comment by feemthan** [comment]
@Encord-davids I did think about this, but wanted to make sure that this does not memory overload the server as copying is always a red flag.

**Comment by Encord-davids** [comment]
> @Encord-davids I did think about this, but wanted to make sure that this does not memory overload the server as copying is always a red flag.

Good point, but since we already use a copy at a later stage I think this is fine (we'll deal with memory issues if they arise in the future)

**Comment by feemthan** [comment]
Ok please feel free to close the pull request then.

**Comment by Encord-davids** [comment]
> Ok please feel free to close the pull request then.

@feemthan thanks a lot for raising this and for flagging this and going through the effort of suggesting a fix 🙌 
Really looking forward to more feedback and contributions 🙏 

Closing this in favour of [PR-160](https://github.com/encord-team/encord-active/pull/160)

**Comment by Encord-davids** [comment]
> Ok please feel free to close the pull request then.

@feemthan thanks a lot for raising this and for flagging this and going through the effort of suggesting a fix 🙌
Really looking forward to more feedback and contributions 🙏

Closing this in favour of https://github.com/encord-team/encord-active/pull/160

**Pull request closed without merging**
